### ISSUE TITLE
Forcing Logging out / Not Refreshing

### ISSUE THREAD

**Issue by gitideas** [aviwad/Friend-Activity-for-Spotify#4] opened 2023-05-25 11:57 UTC
App as been having issues with refresh, forcing you to log out. Log in process does not work every time. Takes many tries, and even when you're back in it does not seem to be working correctly.

Also, would be nice to have album / art cover. (See attached sketch)
![Spotify](https://github.com/aviwad/Friend-Activity-for-Spotify/assets/134607957/11633b19-d0c2-4980-89eb-deecc610d490)

**Comment by aviwad** [comment] 2023-05-25 12:01
Hi! Sorry for the experience you’re having but the screenshots attached are not my app! It’s some shitty competitor lol. Try mine and lemme know. https://apps.apple.com/in/app/spotifriends-friend-activity/id1636288237

**Comment by gitideas** [comment] 2023-05-25 12:03
This is something I sketched, suggesting you should implement this into your app.

**Comment by aviwad** [comment] 2023-05-25 12:37
Ah okay. I’m working on album art. Will be ready soon. Thanks for the designs. Unfortunately they are not efficient. My goal is to match the Spotify Desktop sidebar.

The update i’ll be pushing this week should fix login problems. How did you login? Through email/facebook/google? Can you please give more detail on the issues you faced? Thanks

**Comment by gitideas** [comment] 2023-05-25 13:26
FB login. But after a while the app stops updating. Then you cancel the app, re-open and then you just see the "refresh" button. It never refreshes.

**Comment by samk7752** [comment] 2023-05-26 03:44
Same here, I login through Facebook. After clicking refresh/login a bunch of times (odd time it works) but almost immediately stops working again.

**Comment by aviwad** [comment] 2023-05-26 04:26
Oh okay I’ll have to debug this :( FaceBook login and Google login have been giving me the most stress…

**Comment by aviwad** [comment] 2023-05-26 04:30
How my app authorisation works is to grab an “sp_dc” cookie from spotify servers and use it to login with a 1 hour valid token. then every time that token expires, automatically use the cookie to generate a new token (this cookie is valid for a year). 

Perhaps facebook login tokens are expiring quicker and not working the same way. Will take a look.

**Comment by aviwad** [comment] 2023-05-26 13:19
I have realised something. The same issue has occurred on my phone for the first time. A restart without logging in or out fixes the problem. This makes me think the problem is not with authentication but with the fetch function. I'm not sure why the refresh button isn't working either

**Comment by gitideas** [comment] 2023-05-26 13:55
There seems to be some kind of login issue as well. It's hit or miss.

**Comment by aviwad** [comment] 2023-05-26 14:17
true true. i believe i've fixed login issues on my side. will upload a new build soon, as soon as i fix the UI

**Comment by gitideas** [comment] 2023-05-26 15:02
Cool, guess just throw the update in this thread

**Comment by samk7752** [comment] 2023-05-26 15:49
Thank you guys!

**Comment by aviwad** [comment] 2023-05-27 20:24
So what I figured is removing or adding the widget suddenly makes the app work again. Please try my testflight build and let me know if it fixes all the bugs. thanks a lot again guys!

https://testflight.apple.com/join/W3a22gg0

**Comment by samk7752** [comment] 2023-05-28 08:03
Sadly it’s still not working for me after trying that.

**Comment by aviwad** [comment] 2023-05-28 10:43
@samk7752 were you able to join the testflight build? if it’s still stuck on the refresh screen, can you a) send me a screenshot with all the debug text on the refresh screen and b) if possible, open the Console app on your mac, stream all logging from iphone and click refresh and send the logs if possible

**Comment by aviwad** [comment] 2023-05-31 04:39
HI @gitideas @samk7752 this issue should be fixed in the latest update. Please update through the App Store. Pls reopen the issue if it persists. Thanks.

**Closed as completed by aviwad** 2023-05-31 04:39 UTC

**Comment by gitideas** [comment] 2023-09-15 12:35
Just a heads up again the app is having FB login issues. Somewhere along the process it won't let you confirm login. Could be something with the new iOS, not sure. Saw the most recent app update was 3 months ago so it might be something with the new iOS or with FB. @aviwad
